###
GET http://127.0.0.1:8080/someJSON

###
GET http://127.0.0.1:8080/moreJSON

###
GET http://127.0.0.1:8080/someXML

###
GET http://127.0.0.1:8080/someYAML

###
GET http://127.0.0.1:8080/someProtoBuf
###
POST 127.0.0.1:8080/post?id=1
Content-Type: multipart/form-data;
Content-Disposition: form-data; name="name"

john