// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package alice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AliceClient is the client API for Alice service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AliceClient interface {
	// SayHello 方法
	GetAlice(ctx context.Context, in *AliceRequest, opts ...grpc.CallOption) (*AliceReply, error)
}

type aliceClient struct {
	cc grpc.ClientConnInterface
}

func NewAliceClient(cc grpc.ClientConnInterface) AliceClient {
	return &aliceClient{cc}
}

func (c *aliceClient) GetAlice(ctx context.Context, in *AliceRequest, opts ...grpc.CallOption) (*AliceReply, error) {
	out := new(AliceReply)
	err := c.cc.Invoke(ctx, "/alice.Alice/GetAlice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AliceServer is the server API for Alice service.
// All implementations must embed UnimplementedAliceServer
// for forward compatibility
type AliceServer interface {
	// SayHello 方法
	GetAlice(context.Context, *AliceRequest) (*AliceReply, error)
	mustEmbedUnimplementedAliceServer()
}

// UnimplementedAliceServer must be embedded to have forward compatible implementations.
type UnimplementedAliceServer struct {
}

func (UnimplementedAliceServer) GetAlice(context.Context, *AliceRequest) (*AliceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAlice not implemented")
}
func (UnimplementedAliceServer) mustEmbedUnimplementedAliceServer() {}

// UnsafeAliceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AliceServer will
// result in compilation errors.
type UnsafeAliceServer interface {
	mustEmbedUnimplementedAliceServer()
}

func RegisterAliceServer(s grpc.ServiceRegistrar, srv AliceServer) {
	s.RegisterService(&Alice_ServiceDesc, srv)
}

func _Alice_GetAlice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AliceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AliceServer).GetAlice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/alice.Alice/GetAlice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AliceServer).GetAlice(ctx, req.(*AliceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Alice_ServiceDesc is the grpc.ServiceDesc for Alice service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Alice_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "alice.Alice",
	HandlerType: (*AliceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAlice",
			Handler:    _Alice_GetAlice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "alice/alice.proto",
}
