// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: alice/alice.proto

package alice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 包含人名的一个请求消息
type AliceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *AliceRequest) Reset() {
	*x = AliceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alice_alice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AliceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AliceRequest) ProtoMessage() {}

func (x *AliceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alice_alice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AliceRequest.ProtoReflect.Descriptor instead.
func (*AliceRequest) Descriptor() ([]byte, []int) {
	return file_alice_alice_proto_rawDescGZIP(), []int{0}
}

func (x *AliceRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AliceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// 包含问候语的响应消息
type AliceReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *AliceReply) Reset() {
	*x = AliceReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alice_alice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AliceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AliceReply) ProtoMessage() {}

func (x *AliceReply) ProtoReflect() protoreflect.Message {
	mi := &file_alice_alice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AliceReply.ProtoReflect.Descriptor instead.
func (*AliceReply) Descriptor() ([]byte, []int) {
	return file_alice_alice_proto_rawDescGZIP(), []int{1}
}

func (x *AliceReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_alice_alice_proto protoreflect.FileDescriptor

var file_alice_alice_proto_rawDesc = []byte{
	0x0a, 0x11, 0x61, 0x6c, 0x69, 0x63, 0x65, 0x2f, 0x61, 0x6c, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x61, 0x6c, 0x69, 0x63, 0x65, 0x22, 0x32, 0x0a, 0x0c, 0x41, 0x6c,
	0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x26,
	0x0a, 0x0a, 0x41, 0x6c, 0x69, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x3d, 0x0a, 0x05, 0x41, 0x6c, 0x69, 0x63, 0x65, 0x12,
	0x34, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x69, 0x63, 0x65, 0x12, 0x13, 0x2e, 0x61, 0x6c,
	0x69, 0x63, 0x65, 0x2e, 0x41, 0x6c, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x11, 0x2e, 0x61, 0x6c, 0x69, 0x63, 0x65, 0x2e, 0x41, 0x6c, 0x69, 0x63, 0x65, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x39, 0x5a, 0x37, 0x6b, 0x75, 0x62, 0x65, 0x2d, 0x6c, 0x65,
	0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x2f, 0x70, 0x72, 0x61, 0x63, 0x74, 0x69, 0x73, 0x65, 0x2f,
	0x67, 0x72, 0x70, 0x63, 0x2d, 0x70, 0x72, 0x61, 0x63, 0x74, 0x69, 0x73, 0x65, 0x2f, 0x64, 0x65,
	0x6d, 0x6f, 0x2d, 0x31, 0x2f, 0x61, 0x6c, 0x69, 0x63, 0x65, 0x2f, 0x61, 0x6c, 0x69, 0x63, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_alice_alice_proto_rawDescOnce sync.Once
	file_alice_alice_proto_rawDescData = file_alice_alice_proto_rawDesc
)

func file_alice_alice_proto_rawDescGZIP() []byte {
	file_alice_alice_proto_rawDescOnce.Do(func() {
		file_alice_alice_proto_rawDescData = protoimpl.X.CompressGZIP(file_alice_alice_proto_rawDescData)
	})
	return file_alice_alice_proto_rawDescData
}

var file_alice_alice_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_alice_alice_proto_goTypes = []interface{}{
	(*AliceRequest)(nil), // 0: alice.AliceRequest
	(*AliceReply)(nil),   // 1: alice.AliceReply
}
var file_alice_alice_proto_depIdxs = []int32{
	0, // 0: alice.Alice.GetAlice:input_type -> alice.AliceRequest
	1, // 1: alice.Alice.GetAlice:output_type -> alice.AliceReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_alice_alice_proto_init() }
func file_alice_alice_proto_init() {
	if File_alice_alice_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_alice_alice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AliceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alice_alice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AliceReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_alice_alice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_alice_alice_proto_goTypes,
		DependencyIndexes: file_alice_alice_proto_depIdxs,
		MessageInfos:      file_alice_alice_proto_msgTypes,
	}.Build()
	File_alice_alice_proto = out.File
	file_alice_alice_proto_rawDesc = nil
	file_alice_alice_proto_goTypes = nil
	file_alice_alice_proto_depIdxs = nil
}
